[package]
name = "http"
edition = "2021"
rust-version = "1.65.0"

[dependencies]
bytes = "1"
fnv = "1.0.5"
itoa = "1"

[dev-dependencies]
indexmap = "<=1.8"
quickcheck = "0.9.0"
rand = "0.7.0"
seahash = "3.0.5"
serde = "1.0"
serde_json = "1.0"
doc-comment = "0.3"
criterion = "0.3.2"
